---
title: "ProyectoAED"
# author: "Javier Herrero Pérez"
date: "2025-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Limpieza de los datos

```{r}
rm(list=ls())
```

```{r}
# Ver el tipo de codificación del archivo
archivo<-"data/65948.csv"
guess_encoding(archivo)
```


Cosas que hay que tener en cuenta:

1. En el dataframe los valores NA están identificados como ".." y solo están en la columna Total
2. La marca del decimal está con ","

```{r}
library(readr)
df <-  read_delim(archivo, delim = "\t", escape_double = FALSE, na = "..", trim_ws = TRUE,locale = locale(decimal_mark = ","))
```

```{r}
# Cambiar el nombre de la columna "Relación con la actividad económica" a uno más corto
colnames(df)[3]<-"Situacion_Laboral"
colnames(df)
```


```{r}
# Comprobar los valores NA
sapply(df, function(x) sum(is.na(x)))
# Ver la posición 
which(is.na(df$Total))
```

```{r}
# Eliminar valores NA: son 111 filas en comparación a las 4446 que son en total
df_na<-df[which(is.na(df$Total)),]
```

```{r}
# Guardo el dataframe sin los valores NA
df<-df[-which(is.na(df$Total)),]
```

```{r}
# Comprobar que no hay valores NA:
sapply(df, function(x) sum(is.na(x)))
```

```{r}
# Transformar los datos a su formato real
df$Total<-as.double(df$Total)
df$Sexo<-as.factor(df$Sexo) # "Ambos sexos" "Hombres"     "Mujeres" 
df$Edad<-as.factor(df$Edad)
df$Situacion_Laboral<-as.factor(df$Situacion_Laboral)
str(df)
```


```{r}
levels(df$Situacion_Laboral)
```




